import turtle
def square(a):
    turtle.forward(a)
    turtle.right(80)
    turtle.forward(a)
    turtle.right(10)
    turtle.forward(a)
    turtle.right(80)
    turtle.forward(a)
    turtle.right(10)
    turtle.forward(a)
    turtle.right(80)
    turtle.forward(a)
    turtle.right(50)
    turtle.forward(a)
    turtle.right(10)
    turtle.forward(a)
    turtle.right(80)
    turtle.forward(a)
    turtle.right(10)
    turtle.forward(a)
    turtle.right(60)
    turtle.forward(a)
    turtle.right(10)
    turtle.forward(a)
    turtle.right(80)
    turtle.forward(a)
    turtle.right(30)
    turtle.forward(a)
    turtle.right(10)
    turtle.forward(a)
    turtle.right(80)
    turtle.forward(a)
    turtle.right(80)
    turtle.forward(a)
    turtle.right(90)
    turtle.forward(a)
    turtle.right(90)
    turtle.forward(a)
    turtle.fillcolor('#ff0000')

square(100) # Вызов функции отрисовки квадрата

turtle.done() # Чтобы окно не закрылось